<?php

namespace AppBundle\Repository;

use AppBundle\Repository\MyTrait\AdminTrait;
use Doctrine\ORM\EntityRepository;
use AppBundle\Repository\MyTrait\GeometryTrait;
use AppBundle\Entity\Advertisement;

/**
 * advertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{
    use GeometryTrait;
    use AdminTrait;


    public function getCountNotViewMessages(int $idUser, int $status = 0){
        if (!($idUser > 0) ){
            return;
        }

        $qb = $this->createQueryBuilder('m')
            ->select('count(m.isView) as count, IDENTITY(a.dirStatus) as status')
            ->innerJoin('AppBundle\Entity\Advertisement', 'a', 'with', 'a.id = m.advertisement')
            ->where('a.users = :user')
            ->andWhere('m.isView = false')
            ->setParameter('user', $idUser)
            ->groupBy('a.dirStatus');


        if($status > 0){
            $qb->andWhere('a.dirStatus = :status')
                ->setParameter('status', $status);
            return $qb ->getQuery()
                ->getSingleScalarResult();
        }

        $qb = $qb->getQuery()->getResult();

        return $qb;
    }


}