<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Repository\MyTrait\GeometryTrait;
use AppBundle\Entity\Advertisement;

/**
 * advertisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{
    use GeometryTrait;


    public function getCountNotViewMessages(int $idUser, int $status){
        if (!($idUser > 0) ){
            return;
        }

        $qb = $this->createQueryBuilder('m')
            ->select('count(m)')
            ->innerJoin('AppBundle\Entity\Advertisement', 'a', 'with', 'a.id = m.advertisement')
            ->where('a.users = :user')
            ->andWhere('m.isView = false')
            ->andWhere('m.isView = false')
            ->setParameter('user', $idUser);

        if($status > 0){
            $qb->andWhere('m.isView = false')
                ->setParameter('user', $idUser);
        }



        $qb = $qb ->getQuery()
            ->getSingleScalarResult();

        return $qb;
    }


}