app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

homepage:
    path: /
    defaults:
        _controller: AppBundle:Advertisement:index
        template:    AppBundle:advertisement:index.html.twig

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"